### ISSUE TITLE
Full path needed for `tabe`, relative path does not work

### ISSUE THREAD

**Issue by peterhadlaw** [krisajenkins/evil-tabs#13]
Evil tabs auto completes relative file paths properly but when you try opening a file using a relative path, emacs opens the file relative to the home dir. Maybe my config is wrong but I tried disabling everything but evil tabs and same issue.

**Comment by karepker** [comment]
I also ran into this issue,  and I think I found the culprit and a solution.

[`elscreen-create` does not respect Evil's default directory](https://github.com/knu/elscreen/issues/18), so when [`evil-tabs` calls `elscreen-create` then `find-file`](https://github.com/krisajenkins/evil-tabs/blob/master/evil-tabs.el#L26), `find-file` opens the file relative to the wrong directory.

There are two solutions to this as far as I can tell.

1. Make `elscreen-create` respect `default-directory`, so then `find-file` runs relative to the default directory of the buffer from which you run `:tabe`. I think this is unlikely, considering the [`elscreen` repository](https://github.com/knu/elscreen) hasn't been updated in about a year.
2. Find a different implementation for `:tabe`. Turns out this is actually easy, because `elscreen` offers an `elscreen-find-file` command which appears correctly to open new buffers relative to `default-directory`. I've changed my local copy of `evil-tabs` to use this single call, i.e. replace the lines that call `elscreen-create` and `find-file` to just one line calling `elscreen-find-file`, and relative paths now work! I'll try and send a pull request when I can.
